### ISSUE TITLE
split out references

### ISSUE THREAD

**Issue by jovo** [jovo/cv#47]
i made 3 mendeley groups:
1. https://www.mendeley.com/groups/1680241/neurodata-publications/papers/
2. https://www.mendeley.com/groups/7588651/neurodata-talks/
3. https://www.mendeley.com/groups/7588671/neurodata-posters/

i populated the first one.
let's populate the other two from jovo.bib

then, when new presentations/posters/papers happen, i'll have the lead author update the appropriate group and send me a bibkey.  
i think this will be a better system going forward.

**Comment by wrgr** [comment]
This does seem better.  From a collaboration standpoint, mendeley has
gotten more closed since they were bought by Elsevier, but I don't have an
alternative.  Also, I think restrictions are mostly for closed groups,
which doesn't apply here.

Best,
Will

On Mon, Sep 28, 2015 at 6:48 PM, joshua vogelstein <notifications@github.com
