### ISSUE TITLE
some minor issues

### ISSUE THREAD

**Issue by jovo** [jovo/cv#78]
- knor & sic & LLG & lack arxiv id
- covariate assisted spectral clustering was accepted, add journal?
- in general, lets write "arXiv:XXX.XXX, 2016" rather than "arXiv preprint arXiv:XXX.XXXX, 2016"
- numa optimized is no longer a thing, it was updated with knor
- semi-external memory was published
- M-estimator paper has journal info now
- seeded graph matching is not yet published  #:(
- durante paper journal info looks wrong
- airan paper lacks info
- joint graph paper lacks info
- "stability and localization" is a preprint to the other airan paper, remove
- robust vertex classification is no longer in press, and it is in there twice.
- graph match at your own risk is not in order (it is 2016, but in the 2015s)
- dai paper is also out of order (it is 2012)
- let's link to ROFLMAO, if not SIAM, then our own local copy of pdf
- "M. Fiori, P. Sprechmann, J. Vogelstein, P. Muse, and G. Sapiro. Robust Multimodal Graph Matching: Sparse Coding Meets Graph Matching. Advances in Neural Information Processing Systems (NIPS), pages 127–135, 2013. (spotlight)." "T" is missing in my initials.

**Comment by MrAE** [comment]
- [x] knor & sic & LLG & lack arxiv id
- [x] covariate assisted spectral clustering was accepted, add journal?
- [x]  in general, lets write "arXiv:XXX.XXX, 2016" rather than "arXiv preprint arXiv:XXX.XXXX, 2016"
- numa optimized is no longer a thing, it was updated with knor
- [x] semi-external memory was published
- M-estimator paper has journal info now
- [x] seeded graph matching is not yet published  #:( Moved to works in progress.
- [x] durante paper journal info looks wrong. *updated with bib entry from JASA*
-  [x] airan paper lacks info
- joint graph paper lacks info
-  [x] "stability and localization" is a preprint to the other airan paper, remove
- robust vertex classification is no longer in press, and it is in there twice.
- graph match at your own risk is not in order (it is 2016, but in the 2015s)
- dai paper is also out of order (it is 2012)
-  [x] let's link to ROFLMAO, if not SIAM, then our own local copy of pdf
- [x] "M. Fiori, P. Sprechmann, J. Vogelstein, P. Muse, and G. Sapiro. Robust Multimodal Graph Matching: Sparse Coding Meets Graph Matching. Advances in Neural Information Processing Systems (NIPS), pages 127–135, 2013. (spotlight)." "T" is missing in my initials.

**Comment by jovo** [comment]
@MrAE i did some of these and checked them off.
